---

# tomcat settings
- name: tomcat7 disable java security manager
  lineinfile: dest=/etc/default/tomcat7
    regexp="TOMCAT7_SECURITY"
    line="TOMCAT7_SECURITY=no"

- name: tomcat7 set JAVA_OPTS
  lineinfile: dest=/etc/default/tomcat7
    regexp="^JAVA_OPTS="
    line=JAVA_OPTS="-Djava.awt.headless=true -Xms512M -Xmx512m -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC"

# stop tomcat first
- name: stop tomcat7
  service: name=tomcat7 state=stopped

- name: clean webapp ROOT
  command: >
    rm -rf /var/lib/tomcat7/webapps/ROOT/*

- name: unjar webapp
  command: >
    jar -xf {{ musicbrainz_search_install_directory }}/search-server/servlet/target/searchserver.war
    chdir=/var/lib/tomcat7/webapps/ROOT

# start tomcat again
- name: start tomcat7
  service: name=tomcat7 state=started