---

- name: install nginx package
  apt: pkg=nginx state=present
  tags: packages

- name: ensure nginx default host is absent
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: add nginx config
  template: src=files/musicbrainz.nginx.conf
            dest=/etc/nginx/sites-enabled/musicbrainz.conf

- name: restart nginx
  service: name=nginx state=restarted
  changed_when: false
